config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  api_version = Rails.configuration.x.api.version

  mount OasRails::Engine, at: '/docs'

  root to: redirect('/docs')

  devise_for :users,
             path: "api/#{api_version}",
             path_names: {
               sign_in: 'login',
               sign_out: 'logout',
               registration: 'signup'
             },
             controllers: {
               sessions: 'users/sessions',
               registrations: 'users/registrations',
               confirmations: 'users/confirmations'
             },
             defaults: { format: :json }

  get 'api/v1/user_search', to: 'api#user_search'
  get 'api/v1/user_datas', to: 'api#user_datas'

  namespace :api do
    namespace :v1 do
      mount ActionCable.server => '/cable'
      defaults format: :json do
        resources :appointments, only: %i[index show create update]
        resources :availabilities, only: %i[index create update destroy]
        resources :services, only: %i[index create update]
        resources :customers, only: %i[index]
      end
    end
  end

  devise_for :admins, path: 'admin', controllers: {
    sessions: 'admins/sessions',
    registrations: 'admins/registrations',
    omniauth_callbacks: 'admins/omniauth_callbacks',
    confirmations: 'admins/confirmations'
  }, path_names: {
    sign_in: 'login',
    sign_out: 'logout',
    registration: 'signup'
  }

  devise_scope :admin do
    get '/confirmation-success', to: 'admins/confirmations#success', as: 'confirmation_success'
  end

  authenticate :admin do
    namespace :admins, path: 'admin' do
      get '/', to: 'admins_pages#index', as: :index
      resources :availabilities, only: %i[index create destroy]
      resources :appointments, only: %i[index create destroy]
      resources :services, only: %i[index create destroy]
      resources :users, only: %i[index]
      get 'resetApikey', to: 'admins_pages#resetApikey'
      patch 'updateIpAddress', to: 'admins_pages#updateIpAddress'
    end
  end

  get 'up', to: 'rails/health#show', as: :rails_health_check
end

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand sticky-top">
  <div class="container-fluid">
    <%= link_to "DatesCalendar API", root_path, class: "navbar-brand text-light" %>
    <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
      <div class="navbar-nav justify-content-between w-100">
        <% if request.fullpath.include?("docs") %>
          <%= link_to 'Home', root_path, class: "text-light nav-link #{"active" if request.fullpath.include?("docs")}" %>
          <%= link_to 'Administration', admins_index_path, class:"text-light nav-link"%>
        <% elsif request.fullpath.include?("admin") && current_admin %>
          <div class="d-flex align-items-center">
            <%= link_to 'Home', admins_index_path, class: "text-light nav-link #{"active" if request.fullpath == "/admin"}" %>
            <%= link_to 'Appointments', admins_appointments_path, class:"text-light nav-link #{"active" if request.fullpath.include?("appointments")}" %>
            <%= link_to 'Availabilities', admins_availabilities_path, class:"text-light nav-link #{"active" if request.fullpath.include?("availabilities")}" %>
            <%= link_to 'Services', admins_services_path, class:"text-light nav-link #{"active" if request.fullpath.include?("services")}" %>
            <%= link_to 'Users', admins_users_path, class: "text-light nav-link #{"active" if request.fullpath.include?("users")}" %>
          </div>
          <div class="d-flex align-items-center">
            <%= link_to 'Documentation', root_path, class: "text-light nav-link" %>
            <%= link_to 'Disconnect', destroy_admin_session_path, data: { turbo_method: :delete }, class: 'text-light nav-link' %>
          </div>
        <% else %>
          <div class="d-flex align-items-center">
          </div>
          <div class="d-flex align-items-center">
            <%= link_to 'Documentation', root_path, class: "text-light nav-link" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</nav>